version: '3.4'
networks:
  seven-network:
    driver: bridge

volumes:
  seven-data:
    driver: local

services:
  seven.missioncontrol.server:
    image: ${DOCKER_REGISTRY-}sevenmissioncontrolserver
    ports:
      - 7217:443
      - 5009:80
    build:
      context: .
      dockerfile: SEVEN.MissionControl.Server/Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DB=seven
      - DB_USER=seven
      - DB_PASSWORD=seven
    restart: always
    networks:
      - seven-network      
  postgres:
    container_name: seven-postgres
    image: postgres:latest
    volumes:
      - seven-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=seven
      - POSTGRES_PASSWORD=seven
      - POSTGRES_DB=seven
    networks:
      - seven-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d seven"]
      interval: 5s
      timeout: 5s
      retries: 5