#define HEADLIGHTS_OUTPUT = 13
#define COMMAND_HEADLIGHTS_ON "GET /HL1"
#define COMMAND_HEADLIGHTS_OFF "GET /HL0"
#define COMMAND_CAMERA_TAKEFOTO "GET /CTF"
#define COMMAND_CAMERA_MOVE_LEFT "GET /CML"
#define COMMAND_CAMERA_MOVE_REIGHT "GET /CMR"