name: CI Build and publish API
on:
  push:
    paths:
      - 'SEVEN.MissionControl.Api/**'
      - 'SEVEN.Core/**'
  workflow_dispatch:
jobs:
  Build-And-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3    
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: Build and publish "latest" Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:          
          github-token: '${{ secrets.PACKAGE_TOKEN }}'
          image-name: seven.missioncontrol-api
          dockerfile: ./SEVEN.MissionControl.Api/Dockerfile
