# This is a basic workflow to help you get started with Actions
name: CI-build-and-push-image-for-dotnetapp

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]    
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 docker:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./SEVEN.MissionControl.Server/Dockerfile
          push: true
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/seven-missioncontrol-server:latest, ${{ secrets.DOCKERHUB_USERNAME }}/seven-missioncontrol-server:${{ github.run_number }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/seven-missioncontrol-server:latest
